SmartphoneShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('', include("store.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:smartphoneid>', views.cart_add, name='cart_add'),
	path('remove/<int:smartphoneid>', views.cart_remove, name='cart_remove'),
	path('update/<int:smartphoneid>/<int:quantity>', views.cart_update, name='cart_update'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('', views.index, name="index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('smartphone/<int:id>', views.get_smartphone, name="smartphone"),
	path('smartphones', views.get_smartphones, name="smartphones"),
	path('brand/<int:id>', views.get_smartphone_brand, name="brand"),
	path('contact/', views.contact, name='contact'),
	path('category/<int:id>', views.get_category, name="category"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Smartphone
from .cart import Cart
from django.contrib import messages


def cart_add(request, smartphoneid):
	cart = Cart(request)
	smartphone = get_object_or_404(Smartphone, id=smartphoneid)
	cart.add(smartphone=smartphone)

	return redirect('store:index')


def cart_update(request, smartphoneid, quantity):
	cart = Cart(request)
	smartphone = get_object_or_404(Smartphone, id=smartphoneid)

	if smartphone.stock >= int(quantity):
		cart.update(smartphone=smartphone, quantity=quantity)
		price = smartphone.price * int(quantity)
		return render(request, 'cart/price.html', {"price": price})
	else:
		messages.error(request, "На складе недостаточно смартфонов.")
		return HttpResponse(status=400)



def cart_remove(request, smartphoneid):
    cart = Cart(request)
    smartphone = get_object_or_404(Smartphone, id=smartphoneid)
    cart.remove(smartphone)
    return redirect('cart:cart_details')

def total_cart(request):
	return render(request, 'cart/totalcart.html')

def cart_summary(request):

	return render(request, 'cart/summary.html')

def cart_details(request):
	cart = Cart(request)
	context = {
		"cart": cart,
	}
	return render(request, 'cart/cart.html', context)

templates/cart/cart.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}


{% block container %}
 <section class="cart_area">
      <div class="container">
          <div class="cart_inner">

              <div class="table-responsive">
                   {% if messages %}
					<div class="messages">
					    {% for message in messages %}
					    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
					    {% endfor %}
					</div>
					{% endif %}
                  <table class="table">
                      <thead>


                          <tr>
                              <th scope="col">Продукт</th>
                              <th scope="col">Цена</th>
                              <th scope="col">Количество</th>
                              <th scope="col">Итого</th>
                              <th scope="col">Удалить</th>
                          </tr>
                      </thead>
                      <tbody>
                      {% for item in cart %}
                         {% with smartphone=item.smartphone %}
                          <tr>
                              <td>
                                  <div class="media">
                                      <div class="d-flex cart_coverpage">
                                        <a href=""><img src="{{ smartphone.image.url }}" alt=""></a>
                                      </div>
                                      <div class="media-body">
                                          <p>{{ smartphone.name }} ({{ smartphone.storage}}гб)</p>
                                      </div>
                                  </div>
                              </td>
                              <td>
                                  <h5>{{ smartphone.price }}$</h5>
                              </td>
                              <td class="cart_quantity">
                                    <input type="text" name="qty" value="{{ item.quantity }}" onchange="updateCartItem(this,{{ smartphone.id }})" >


                              </td>

                              <td>
                                  <h5 id="{{ smartphone.id }}">{{ item.total_price }}$</h5>
                              </td>
                              <td>
                                <a href="{% url 'cart:cart_remove' smartphoneid=smartphone.id %}" class="btn btn-danger">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                          </tr>
                      <tr class="out_button_area">
                              <td class="d-none-l">

                              </td>
                              <td class="">

                              </td>
                              <td>

                              </td>
                              <td>
                                  <div class="checkout_btn_inner d-flex align-items-center">
										  <a class="gray_btn" href="{% url 'store:index' %}">Продолжить покупки</a>
                                      <a class="primary-btn ml-2" href="{% url 'order:order_create' %}">Переходить к оформлению заказа</a>
                                  </div>
                              </td>
                          </tr>
                      {% endwith %}
                {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </section>
{% endblock %}

templates/cart/price.html
{{ price }} $.

templates/cart/summary.html
{% load customfunction %}
<ul class="list-group">
	<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Checkout Summary</h4></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Smartphone<span>{{ cart|length }}</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Subtotal<span>{{ cart.get_total_price }} $.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Shipping<span>{{ cost|shipping }} $.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ cart.get_total_price|payabletotal}} $.</span></li>
</ul>	

templates/cart/totalcart.html
{{ cart|length }}