SmartphoneShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('', include("store.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:smartphoneid>', views.cart_add, name='cart_add'),
	path('remove/<int:smartphoneid>', views.cart_remove, name='cart_remove'),
	path('update/<int:smartphoneid>/<int:quantity>', views.cart_update, name='cart_update'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('', views.index, name="index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('smartphone/<int:id>', views.get_smartphone, name="smartphone"),
	path('smartphones', views.get_smartphones, name="smartphones"),
	path('brand/<int:id>', views.get_smartphone_brand, name="brand"),
	path('contact/', views.contact, name='contact'),
	path('category/<int:id>', views.get_category, name="category"),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    logo = models.FileField(upload_to="brand/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    icon = models.FileField(upload_to="category/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Smartphone(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    image = models.FileField(upload_to="smartphones/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField()
    screen_size = models.CharField(max_length=50)
    battery_capacity = models.CharField(max_length=50)
    ram = models.CharField(max_length=50)
    storage = models.CharField(max_length=50)
    camera_resolution = models.CharField(max_length=50)
    processor = models.CharField(max_length=50)
    totalreview = models.IntegerField(default=1)
    totalrating = models.IntegerField(default=5)

    def __str__(self):
        return self.name

class Review(models.Model):
	customer = models.ForeignKey(User, on_delete=models.CASCADE)
	smartphone = models.ForeignKey(Smartphone, on_delete=models.CASCADE)
	review_star = models.IntegerField()
	review_text = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

store/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Review
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'name',
            'email',
            'username',
            'password1',
            'password2'
        ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('User with this email already exists.')
        return email

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class ReviewForm(forms.ModelForm):
    review_star = forms.IntegerField(widget=forms.HiddenInput(), initial=1)
    review_text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write Your Review'}))

    class Meta:
        model = Review
        fields = [
            'review_star',
            'review_text'
        ]

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Brand, Category, Smartphone, Review
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import RegistrationForm, ReviewForm


def index(request):
    new_smartphones = Smartphone.objects.order_by('-created_at')[:15]
    best_smartphones = Smartphone.objects.order_by('-totalrating')
    context = {
        "new_smartphones": new_smartphones,
        "best_smartphones": best_smartphones,
    }
    return render(request, 'store/index.html', context)


def signin(request):
    if request.user.is_authenticated:
        return redirect('store:index')
    else:
        if request.method == "POST":
            user = request.POST.get('user')
            password = request.POST.get('pass')
            auth = authenticate(request, username=user, password=password)
            if auth is not None:
                login(request, auth)
                return redirect('store:index')
            else:
                messages.error(request, 'Имя пользователя и пароль не совпадают.')

    return render(request, "store/login.html")


def signout(request):
    logout(request)
    return redirect('store:index')



def registration(request):
    if request.user.is_authenticated:
        return redirect('store:index')

    form = RegistrationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']


            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Аккаунт был создан успешно")
                return redirect('store:index')
            else:
                messages.error(request, "Не удалось войти в систему после регистрации.")
        else:
            for error in form.errors.values():
                messages.error(request, error)

    return render(request, 'store/signup.html', {"form": form})



def payment(request):
    return render(request, 'store/payment.html')


def get_smartphone(request, id):
    form = ReviewForm(request.POST or None)
    smartphone = get_object_or_404(Smartphone, id=id)
    related_smartphones = Smartphone.objects.filter(category_id=smartphone.category.id)
    related_reviews = Review.objects.filter(smartphone_id=id).order_by('created')

    paginator = Paginator(related_reviews, 4)
    page = request.GET.get('page')
    r_review = paginator.get_page(page)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if form.is_valid():
                temp = form.save(commit=False)
                temp.customer = User.objects.get(id=request.user.id)
                temp.smartphone = smartphone

                temp = Smartphone.objects.get(id=id)
                temp.totalreview += 1
                temp.totalrating += int(request.POST.get('review_star'))
                temp.save()
                form.save()
                messages.success(request, "Отзыв успешно добавлен.")
                form = ReviewForm()
        else:
            messages.error(request, "Сначала вам нужно войти в систему.")

    context = {
        "smartphone": smartphone,
        "related_smartphones": related_smartphones,
        "form": form,
        "related_reviews": r_review
    }
    return render(request, "store/smartphone.html", context)



def get_smartphones(request):
    smartphones_ = Smartphone.objects.all().order_by('created_at')
    paginator = Paginator(smartphones_, 5)
    page_number = request.GET.get('page')
    smartphones = paginator.get_page(page_number)
    return render(request, "store/brand.html", {"smartphone": smartphones})

def get_smartphone_brand(request, id):
    brand = get_object_or_404(Brand, id=id)
    smartphone_ = Smartphone.objects.filter(brand_id=id)
    paginator = Paginator(smartphone_, 10)
    page_number = request.GET.get('page')
    smartphone = paginator.get_page(page_number)
    return render(request, "store/brand.html", {"smartphone": smartphone, "brand": brand})


def get_category(request, id):
    category = get_object_or_404(Category, id=id)
    smartphones = Smartphone.objects.filter(brand_id=category.id)
    context = {
        "category": category,
        "smartphones": smartphones
    }
    return render(request, "store/brand.html", context)

def contact(request):
    return render(request, 'store/contact.html')

templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Smartphone Shop</title>
  {% load static %}


  <link rel="icon" href="img/Fevicon.png" type="image/png">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.3.0/jquery.bootstrap-touchspin.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static  'bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'nice-select/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.min.css' %}">


  <link rel="stylesheet" href="{% static 'css/style2.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>


{% include 'store/bin/header.html' %}


{% block container %}{% endblock %}



{% include 'store/bin/footer.html' %}

<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>

  <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Readmore.js/2.2.1/readmore.js" type="text/javascript"></script>
  <script src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script>
  <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/skrollr.min.js' %}"></script>
  <script src="{% static 'owl-carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'nice-select/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'js/main2.js' %}"></script>

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function(){
            summary();
        });

        function summary(){
            $.ajax({
                url : "summary",
                type : "GET",
                success : function(data){
                    $("#abc").html(data);
                }
            });
        }

        function updateCartItem(obj, id){
            $.ajax({
                url: "update/" + id + "/" + obj.value,
                type: "GET",
                data: {
                    smartphoneid: id,
                    quantity: obj.value
                },
                success: function(data){
                    $("#" + id).html(data);
                    summary();
                    totalCart();
                }
            });
        }



    </script>
{% endblock %}

</body>
</html>

templates/store/brand.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}

{% block headermenu %}

{% endblock %}
{% block container %}
	<section class="blog-banner-area" id="contact">
 				<div class="container h-100">
					<div class="blog-banner">
						<div class="text-center">
							<h1> Смартфоны </h1>
							<nav aria-label="breadcrumb" class="banner-breadcrumb">
					<ol class="breadcrumb">
					  <li class="breadcrumb-item"><a>Удивительные смартфоны</a></li>
					</ol>
				  </nav>
						</div>
					</div>
			</div>

			</section>
		<section class="section-margin calc-60px">
     <div class="container">
    <div class="row">
        {% for item in smartphone %}
        <div class="col-md-3 mb-4">
            <div class="card text-center card-product">
                <div class="card-product__img">
                    <img class="card-img" src="{{ item.image.url }}" alt="">
                    <ul class="card-product__imgOverlay">
                        <li><button id="addTocart" data-book-id="{{ item.id }}">
                            <i class="fa fa-shopping-cart"></i>
                        </button></li>
                    </ul>
                </div>
                <div class="card-body">
                    <p>{{ item.brand }}</p>
                    <h4 class="card-product__title"><a href="{% url 'store:smartphone' id=item.id %}">{{ item.name|text_short }} ({{ item.storage }} гб.)</a></h4>
                    <p class="card-product__price">{{ item.price }}$.</p>
                    <div class="rating">
                        {% if item.totalreview == 0 %}
                            <span class="totalrating">Нет отзывов</span>
                        {% else %}
                            {{ item.totalrating|averagerating:item.totalreview }}
                            <span class="totalrating">{{ item.totalreview }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
		 {% if smartphone|length > 0 %}
			<div class="d-pagination">
			    <ul class="pagination">
				{% if smartphone.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">Первый</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ smartphone.previous_page_number }}">Назад</a>
					</li>
				{% endif %}
				{% for ord in smartphone.paginator.page_range %}
					{% if smartphone.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(current)</span>
							</span>
						</li>
					{% elif ord > smartphone.number|add:'-3' and ord < smartphone.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				{% if smartphone.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ smartphone.next_page_number }}">Следующий</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ smartphone.paginator.num_pages }}">Последний</a>
					</li>
				{% endif %}
			    </ul>
			</div>
			{% else %}




			<h3 class="text-center mt-5">Не найдены смартфоны.</h3>

			{% endif %}

</div>




		</section>
<div id="snackbar"></div>


{% endblock %}

templates/store/category.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}



			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="view-details">
								<img src="{{ category.icon.url }}">
							</div>
						</div>
						
						<div class="col-sm-8">
							<div class="product-information">
								<h3>{{ category.name }}</h3>
								<article class="text-justify" style="margin-top:10px;">{{ category.description }}</article>

							</div>
						</div>
					</div>	
				</div>

				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">Published Books</h3>
					</div>
					<div class="regulara sliderzx">
						{% for item in smartphones %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.image.url }}"/>
							</div>
							<a href="{% url 'store:smartphone' id=item.id %}">{{ item.name|text_short }}</a>
							<a href="{% url 'store:category' id=item.writer.id %}">{{ item.category }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview }}</span>
							</div>
							<p> ${{ item.price }} </p>
							<button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
									<i class="fa fa-shopping-cart""></i>Add to cart
							</button>


						</div>
						{% endfor %}
					</div>
				</div>
			</div>
{% endblock %}

templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}

  <main class="site-main">

    <section class="hero-banner">
      <div class="container">
        <div class="row no-gutters align-items-center pt-60px">
          <div class="col-5 d-none d-sm-block">
            <div class="hero-banner__img">
              <img class="img-fluid" src="{% static 'img/main_logo.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-s m-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
            <div class="hero-banner__content">
              <h5>Исследовать магазин - это весело</h5>
              <h2>Ознакомьтесь с нашими смартфонами Премиум-класса</h2>
			<p>Добро пожаловать в SmartphoneShop! Насладитесь удобством онлайн-покупок, где каждый смартфон - это инновация, пользоваться которой приятно.</p>
                <a class="button button-hero" href="{% url 'store:smartphones' %}">Исследовать</a>
            </div>
          </div>
        </div>
      </div>
    </section>
 <section class="section-margin calc-60px">
      <div class="container">
        <div class="section-intro pb-60px">
		<p>Новинка в магазине</p>
			<h2>Новые <span class="section-intro__style">Смартфоны</span></h2>
        </div>
        <div class="owl-carousel owl-theme"  id="popularCarousel" >
          {% for item in new_smartphones %}

          <div class="card text-center card-product">
            <div class="card-product__img">
              <img class="card-img" src="{{ item.image.url }}" alt="">
              <ul class="card-product__imgOverlay">

                <li><button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
                  <i class="fa fa-shopping-cart"></i>
                </button></li>
              </ul>
            </div>
            <div class="card-body">
                <p>{{ item.brand }}</p>
                <h4 class="card-product__title"><a href="{% url 'store:smartphone' id=item.id %}">{{ item.name|text_short }} ({{ item.storage }} гб.)</a></h4>
                <p class="card-product__price">{{ item.price }}$.</p>
                <div class="rating">
                  {% if item.totalreview == 0 %}
                      <span class="totalrating">Нет отзывов</span>
                  {% else %}
                      {{ item.totalrating|averagerating:item.totalreview }}
                      <span class="totalrating">{{ item.totalreview }}</span>
                  {% endif %}
                </div>
            </div>
          </div>

         {% endfor %}
        </div>
      </div>
    </section>


    <section class="section-margin calc-60px">
      <div class="container">
        <div class="section-intro pb-60px">
          <p>Популярные смартфоны на рынке</p>
          <h2>Лучшие <span class="section-intro__style">Смартфоны</span></h2>
        </div>
        <div class="owl-carousel owl-theme" id="bestSellerCarousel">
          {% for item in best_smartphones %}

          <div class="card text-center card-product">
            <div class="card-product__img">
              <img class="card-img" src="{{ item.image.url }}" alt="">
              <ul class="card-product__imgOverlay">

                <li><button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
                  <i class="fa fa-shopping-cart"></i>
                </button></li>
              </ul>
            </div>
            <div class="card-body">
                <p>{{ item.brand }}</p>
                <h4 class="card-product__title"><a href="{% url 'store:smartphone' id=item.id %}">{{ item.name|text_short }}</a></h4>
                <p class="card-product__price">{{ item.price }}$.</p>
                <div class="rating">
                  {% if item.totalreview == 0 %}
                      <span class="totalrating">Нет отзывов</span>
                  {% else %}
                      {{ item.totalrating|averagerating:item.totalreview }}
                      <span class="totalrating">{{ item.totalreview }}</span>
                  {% endif %}
                </div>
            </div>
          </div>

         {% endfor %}
        </div>
      </div>
    </section>





  </main>
<div id="snackbar"></div>
{% endblock %}

templates/store/login.html
{% extends 'store/base.html' %}
{% load static %}
{% block container %}
<section class="login_box_area section-margin">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<div class="hover">
							<h4>Вы новичок на нашем сайте?</h4>
							<a class="button button-account" href="{% url 'store:registration' %}">Создать аккаунт</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner">
					{% if messages %}
					<div class="messages">

					</div>
					{% endif %}
						<h3>Войдите в систему</h3>
						<form class="row login_form" action="#/" id="contactForm" method="POST" >
							{% csrf_token %}

							<div class="col-md-12 form-group">
								<input type="text" class="form-control"  name="user" placeholder="Имя пользователя" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
                                {% if messages %}
                                {% for message in messages %}
                                    <p style="color: red;font-size: 13px">{{ message }}</p>
                                {% endfor %}
                                {% endif %}


							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" name="pass" placeholder="Пароль" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>

							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="button button-login w-100">Войти</button>

							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/store/signup.html
{% extends 'store/base.html' %}
{% load static %}
{% block container %}
<section class="login_box_area section-margin">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <div class="hover">
                        <h4>Уже есть аккаунт?</h4>
                        <a class="button button-account" href="{% url 'store:signin' %}">Войти</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner register_form_inner">

                    <h3>Создать аккаунт</h3>
                    <form class="login_form" action="{% url 'store:registration' %}" method="POST" id="register_form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group col-md-12">
                                <input type="{{ field.field.widget.input_type }}"
                                       class="form-control"
                                       id="{{ field.id_for_label }}"
                                       name="{{ field.html_name }}"
                                       placeholder="{{ field.label }}"
                                       {% if field.field.required %}required{% endif %}>

                                {% for error in field.errors %}
                                    <p style="color: red;font-size: 13px">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}


                        <div class="form-group col-md-12">
                            <button type="submit" value="submit" class="button button-register w-100">Создать аккаунт</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/store/smartphone.html
{% extends 'store/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load customfunction %}
{% block container %}
	<div class="product_image_area">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
						<div class="single-prd-item">
							<img class="card-img" src="{{ smartphone.image.url }} " alt="">
						</div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3>{{ smartphone.name }}</h3>
						<h2>{{ smartphone.price }}$</h2>
						<ul class="list">
							<li><a class="active"><span><b>Категория:</b></span> {{ smartphone.category }}</a></li>
							<li><a ><span><b>Количество:</b></span> {{ smartphone.stock }}</a></li>
							<li><a ><span><b>Размер экрана:</b></span> {{ smartphone.screen_size }}</a></li>
							<li><a ><span><b>Емкость батареи:</b></span> {{ smartphone.battery_capacity }}мАч</a></li>
							<li><a ><span><b>ОЗУ:</b></span> {{ smartphone.ram }}ГБ</a></li>
							<li><a ><span><b>Память:</b></span> {{ smartphone.storage }}ГБ</a></li>
							<li><a ><span><b>Камера:</b></span> {{ smartphone.camera_resolution }}МП</a></li>
							<li><a ><span><b>Процессор:</b></span> {{ smartphone.processor }}</a></li>
						</ul>
						<p>{{ smartphone.description }}</p>
						<div class="product_count">
							<a class="button primary-btn" id="addTocart" data-book-id="{{ smartphone.id }}" href="#">
								Добавить в корзину
							</a>

						</div>

					</div>
				</div>
				 <div class="col-sm-9 mt-5" id="getreview">
					{% if constants %}
						<div class="messages">
						    {% for message in messages %}
						    <p{% if messages.tags %} class="{{ messages.tags }}"{% endif %}>{{ messages }}</p>
						    {% endfor %}
						</div>
					{% endif %}
					<div class="rating-stars text-left">
						<ul id="stars">
						  <li id="azaa" class="star" data-value="1"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azbb" class="star" data-value="2"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azcc" class="star" data-value="3"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azdd" class="star" data-value="4"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azee" class="star" data-value="5"> <i class="fa fa-star fa-fw"></i> </li>
						</ul>
					</div>
				 {% if user.is_authenticated %}
				   <form action="" method="POST" class="needs-validation" novalidate="">
				   	{% csrf_token %}

						<div class="form-group">
							{{ form.review_star|as_crispy_field }}
						</div>
						<div class="form-group">
							{{ form.review_text|as_crispy_field }}
						</div>
						<div class="form-group">
							<button class="btn btn-warning" type="submit" style="color: #fff">Submit </button>
						</div>
				   </form>
				   {% else %}
				   	<p>Пожалуйста, <a href="{% url 'store:signin' %}">войдите</a> или <a href="{% url 'store:registration' %}">зарегистрируйтесь</a>, чтобы оставить отзыв.</p>
				   {% endif %}
					{% for lreview in related_reviews %}
					<div class="card">
						<div class="card-body">
							<b> {{ lreview.customer }} </b>
							<div class='rating'>
								{{ lreview.review_star|averagerating:1 }}
							</div>
							<div class="given_review_date">
								<span style="color:#555;"> {{ lreview.created }}</span>
							</div>
							<p style="margin-top: 10px"> {{ lreview.review_text }} </p>
						 </div>
					</div>
					{% endfor %}

					<div class="d-pagination">
					    <ul class="pagination">
						{% if related_reviews.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?page=1">Первый</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ related_reviews.previous_page_number }}">Предыдущий</a>
							</li>
						{% endif %}
						{% for ord in related_reviews.paginator.page_range %}
							{% if related_reviews.number == ord %}
								<li class="page-item active">
									<span class="page-link">{{ ord }}
										<span class="sr-only">(current)</span>
									</span>
								</li>
							{% elif ord > related_reviews.number|add:'-3' and ord < related_reviews.number|add:'3' %}
								<li class="page-item">
									<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
								</li>

							{% endif %}

						{% endfor %}
						 {% if related_reviews.has_next %}
							<li class="page-item">
								<a class="page-link" href="?page={{ related_reviews.next_page_number }}">Следующий</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ related_reviews.paginator.num_pages }}">Последний</a>
							</li>
						{% endif %}
					    </ul>
					</div>
				</div>
			</div>
			<div id="snackbar"></div>

		</div>

	</div>

{% endblock %}