SmartphoneShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('', include("store.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:smartphoneid>', views.cart_add, name='cart_add'),
	path('remove/<int:smartphoneid>', views.cart_remove, name='cart_remove'),
	path('update/<int:smartphoneid>/<int:quantity>', views.cart_update, name='cart_update'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

order/models.py
from django.db import models
from store.models import Smartphone
from django.contrib.auth.models import User


class Order(models.Model):
	customer = models.ForeignKey(User, on_delete = models.CASCADE)
	name = models.CharField(max_length=30)
	email = models.EmailField()
	phone = models.CharField(max_length=16)
	address = models.CharField(max_length=150)
	payment_method = models.CharField(max_length = 20)
	payable = models.IntegerField()
	totalsmartphone = models.IntegerField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created', )

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    smartphone = models.ForeignKey(Smartphone, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

order/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):




	class Meta:
		model = Order
		fields = ['name', 'email', 'phone', 'address']

order/views.py
from django.http import Http404
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from django.core.paginator import Paginator
from cart.cart import Cart
from .models import Order, OrderItem
from .forms import OrderCreateForm
from .pdfcreator import renderPdf


def order_create(request):
    cart = Cart(request)
    if request.user.is_authenticated:
        customer = get_object_or_404(User, id=request.user.id)
        form = OrderCreateForm(request.POST or None, initial={"name": customer.first_name, "email": customer.email})
        if request.method == 'POST':
            if form.is_valid():
                order = form.save(commit=False)
                order.customer = User.objects.get(id=request.user.id)
                order.payable = cart.get_total_price()
                order.totalsmartphone = len(cart)
                order.save()

                for item in cart:
                    OrderItem.objects.create(
                        order=order,
                        smartphone=item['smartphone'],
                        price=item['price'],
                        quantity=item['quantity']
                    )
                cart.clear()
                return render(request, 'order/successfull.html', {'order': order})

            else:
                messages.error(request, "Правильно заполните свои данные.")

        if len(cart) > 0:
            return render(request, 'order/order.html', {"form": form})
        else:
            return redirect('store:smartphone')
    else:
        return redirect('store:signin')


def order_list(request):
    my_order = Order.objects.filter(customer_id=request.user.id).order_by('-created')
    paginator = Paginator(my_order, 5)
    page = request.GET.get('page')
    myorder = paginator.get_page(page)

    return render(request, 'order/list.html', {"myorder": myorder})


def order_details(request, id):
    order_summary = get_object_or_404(Order, id=id)

    if order_summary.customer_id != request.user.id:
        return redirect('store:index')

    orderedItem = OrderItem.objects.filter(order_id=id)
    context = {
        "o_summary": order_summary,
        "o_item": orderedItem
    }
    return render(request, 'order/details.html', context)


class pdf(View):
    def get(self, request, id):
        try:
            query = get_object_or_404(Order, id=id)
        except:
            Http404('Нет контента')
        context = {
            "order": query
        }
        article_pdf = renderPdf('order/pdf.html', context)
        return HttpResponse(article_pdf, content_type='application/pdf')

templates/order/details.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-8">
					<div class="cart_info">
					    <table class="table table-hover">
					        <thead class="text-center">
					            <tr>
					                <th scope="col">#</th>
					                <th scope="col" style="width: 250px">Имя</th>
					                <th scope="col">Цена</th>
					                <th scope="col" >Кол-во</th>
					                <th scope="col">Промежуточный итог</th>
					            </tr>
					        </thead>
					        <tbody class="text-center">
					        	{% for item in o_item %}
					            <tr>
					                <td class="cart_coverpage"><a href=""><img src="{{ item.smartphone.smartphone.url}}"></a></td>
					                <td><a href="{% url 'store:book' id=item.smartphone.id %}">{{ item.book.name }}</a></td>
					                <td class="cart_quantity">{{ item.smartphone.price }} $.</td>
					                <td class="cart_quantity">{{ item.quantity }}</td>
					                <td>{{ item.book.price|subtotal:item.quantity }} $.</td>
					            </tr>
					            {% endfor %}
					        </tbody>
					    </table>
					</div>
				</div>
				<div class="col-sm-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Сводка</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Смартфоны<span>{{ o_summary.totalsmartphone }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Промежуточный итог<span>{{ o_summary.payable }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Доставка<span>{{ 100 }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Итого к оплате<span>{{ o_summary.payable|add:100 }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Дата заказа<span>{{ o_summary.created }}</span></li>
					</ul>
				</div>
			</div>
		{% endblock %}

templates/order/list.html
{% extends 'store/base.html' %}
{% load static %}
{% block container %}
			<div class="cart_info">
			    <table class="table table-hover">
			        <thead class="text-center">
			            <tr>
			                <th scope="col">#</th>
			                <th scope="col">Payment</th>
			                <th scope="col">Qty</th>
			                <th scope="col">Status</th>
			                <th scope="col">Date</th>
			            </tr>
			        </thead>
			        <tbody class="text-center">
			            {% for morder in myorder %}
			            <tr>
			                <td>{{ forloop.counter }}</td>
			                <td>{{ morder.payable }} $.</td>
			                <td>{{ morder.totalsmartphone }}</td>
			                <td class="text-center">
			                	{% if morder.paid == True %}
			                	<p class="status3">Подтвержденный</p>
			                	{% else %}
			                	<p class="status1">Скоро доставим</p>
			                	{% endif %}
			                </td>
			                <td>{{ morder.created }}</td>
			            </tr>
			        	{% endfor %}
			        </tbody>
			    </table>
			</div>

			<div class="d-pagination">
			    <ul class="pagination">
				{% if myorder.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">Первый</a>
					</li>								
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.previous_page_number }}">Назад</a>
					</li>
				{% endif %}
				{% for ord in myorder.paginator.page_range %}
					{% if myorder.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(current)</span>
							</span>
						</li>
					{% elif ord > myorder.number|add:'-3' and ord < myorder.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				 {% if myorder.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.next_page_number }}">Следующий</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.paginator.num_pages }}">Последний</a>
					</li>
				{% endif %}
			    </ul>
			</div>

		{% endblock %}

templates/order/order.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% load crispy_forms_tags %}

{% block container %}

<section class="checkout_area section-margin--small">

    <div class="container">
    <div class="row">


           <div class="col-md-8 order-md-1 cart_info">
			        <h4 class="mb-3 mt-3">Адрес доставки</h4>
					{% if messages %}
					<div class="messages">
					    {% for message in messages %}
					    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
					    {% endfor %}
					</div>
					{% endif %}
			        <form action="" method="POST" class="needs-validation" novalidate="">
			        	{% csrf_token %}
			            <div class="row">
			                <div class="col-md-6 mb-3">
			                    {{ form.name|as_crispy_field }}
			                </div>
			                <div class="col-md-6 mb-3">

			                   	{{ form.email|as_crispy_field }}
			                </div>
			            </div>
	           			<div class="mb-3">
			                {{ form.phone|as_crispy_field }}
			            </div>

			            <div class="mb-3">
			                {{ form.address|as_crispy_field }}
			            </div>

			            <hr class="mb-4">


			            <hr class="mb-4">
			            <button class="btn btn-warning btn-block" type="submit" style="margin-bottom: 20px">Продолжить оформлять заказ</button>
			        </form>
			    </div>
			    <div class="col-md-4 order-md-2 mb-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Сводка</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Смартфон<span>{{ cart|length }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Промежуточный итог<span>{{ cart.get_total_price }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Доставка<span>{{ cost|shipping }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Итого к оплате<span>{{ cart.get_total_price|payabletotal}} $.</span></li>
					</ul>
			    </div>
    </div>
    </div>
			 </section>>

		{% endblock %}

templates/order/pdf.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Book Store Sign In</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">

</head>
<body>
	<div class="container">
		<div class="row justify-content-md-center">
	        <div class="col-md-12 cart_info">
		        <div class="ordered-info">

		                <h1>Smartphone: {{ order.totalsmartphone }}</h1>
		                <h1>Name: {{ order.name }}</h1>
		                <h1>Number: {{ order.phone }}</h1>
		                <h1>Email: {{ order.email }}</h1>
		                <h1>Adress: {{ order.address }}</h1>
		        </div>
	        </div>
		</div>
	</div> 
</body>
</html>

templates/order/successfull.html
{% extends 'store/base.html' %}
{% load static %}

{% block container %}
    <section class="cart_area">
        <div class="container">
          <div class="cart_inner">
              <div class="table-responsive">
            <div class="col-md-12 cart_info">
                    <div class="successful-order text-center">
                        <h3 class="page-header">Спасибо за покупку!</h3>
                    </div>
                   <table class="table ordered-info">
                      <thead>

                          <tr>
                              <th scope="col">#</th>
                              <th scope="col">Смартфон</th>
                              <th scope="col">Имя</th>
                              <th scope="col">Телефон</th>
                              <th scope="col">Почта</th>
                              <th scope="col">Адрес доставки</th>
                          </tr>
                      </thead>
                      <tbody>
                          <tr>
                              <td>
                                  <h5>{{ order.id }}</h5>
                              </td>
                              <td>
                                  <h5>{{ order.totalsmartphone }}</h5>
                              </td>
                              <td>
                                  <div class="media">

                                      <div class="media-body">
                                          <h5>{{ order.name }}</h5>
                                      </div>
                                  </div>
                              </td>
                              <td>
                                  <h5>{{ order.phone }}</h5>
                              </td>
                              <td>
                                  <h5>{{ order.email }}</h5>
                              </td>
                              <td>
                                  <h5>{{ order.address }}</h5>
                              </td>


                          </tr>
                      </tbody>
                   </table>
                <center>
                    <div class="download-info">
                        <a href="{% url 'order:pdf' id=order.id %}">Скачать файл</a>
                    </div>
                </center>
            </div>
            </div>
            </div>
            </div>
    </section>
{% endblock %}